- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Enable and start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
